### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by jshwaluk** [conancat/mongoose-redis-cache#11]
Can you bump the version in package.json from 0.0.3 please?  It's preventing the install of the latest version of this great package via npm.

There was a critical fix here: https://github.com/conancat/mongoose-redis-cache/commit/7e75f0c2fc818a1ce4dd5baa6675ab2bbff72a04

Thanks!

**Comment by lbeschastny** [comment]
It looks like @conancat abandoned this project. =(

**Comment by jshwaluk** [comment]
Bah - ok thanks for the heads up.

**Comment by lbeschastny** [comment]
@jshwaluk if you need a stable version of this project you may use my fork [Intervox/mongoose-redis-cache](https://github.com/Intervox/mongoose-redis-cache/).
